/**
 * Unit tests for the CATT Anti-Cheat Engine / Judge (PRD 3.2).
 *
 * Runner: Node's built-in test runner, no dependencies, no database, no HTTP.
 *   cd backend-server && node --test test/anticheat.test.js
 *
 * The telemetry fixtures live in THIS file (not in src/) because they are
 * test data, not production code. They are exported so the server tests can
 * reuse the same realistic streams when it needs to drive a real route.
 * Every fixture is generated by a local seeded LCG, so the "random" data is
 * byte-identical on every run: these tests can never flake.
 */

const test = require("node:test");
const assert = require("node:assert/strict");

const {
  FLAGS,
  SUBMISSION_FLAGS,
  FLAGS_PENALTIES,
  STATUS,
  PASS,
  FAIL,
  MIN_TELEMETRY_SAMPLES,
  TELEMETRY_PASS_SCORE,
  SCROLL_MAX_PX_PER_SECOND,
  MIN_TYPING_MS_PER_CHAR,
  SYNDICATE_SIMILARITY_THRESHOLD,
  evaluateTelemetry,
  isTelemetryAcceptable,
  evaluateSubmission,
  similarity,
  normalizeText,
  detectSyndicate,
} = require("../src/anticheat.js");

const { getArticle, getMission } = require("../src/content.js");

/* -------------------------------------------------------------------------- */
/* Deterministic fixture generator (test-only, never Math.random)              */
/* -------------------------------------------------------------------------- */

/**
 * mulberry32, duplicated here on purpose: the fixtures must not depend on the
 * module under test, or a PRNG bug would cancel itself out.
 *
 * @param {number} seed
 * @returns {() => number} Floats in [0, 1).
 */
function _rng(seed) {
  let a = seed >>> 0;
  return function next() {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const SAMPLE_INTERVAL_MS = 5000; // PRD 3.1: telemetry is posted every 5 seconds.
const START_TS = 1717000000000; // fixed epoch base, so fixtures never drift

/**
 * A HUMAN reading on a mid-range Android phone: ~2.5 minutes of reading, 30
 * telemetry samples, battery temperature drifting up under load and settling
 * back down, integer touch coordinates that never repeat, and scroll deltas
 * consistent with a thumb flicking through a page.
 *
 * @param {number} [count]
 * @returns {Array<{ ts: number, batteryTempC: number, touch: { x: number, y: number }, scrollDelta: number }>}
 */
function humanTelemetry(count = 30) {
  const rng = _rng(0xc0ffee);
  const samples = [];
  let temp = 29.4; // phone idle-ish in a room at ~22C
  const touches = new Set();
  for (let i = 0; i < count; i += 1) {
    // Heat up under sustained load, cool slightly on the pause samples: the
    // series is a drift, never a constant.
    temp += (rng() - 0.42) * 0.9;
    if (temp < 25) temp = 25 + rng() * 0.4;
    if (temp > 40) temp = 40 - rng() * 0.4;

    let x = 0;
    let y = 0;
    let key = "";
    for (let tries = 0; tries < 64; tries += 1) {
      x = Math.floor(rng() * 1080); // integer pixel coordinates
      y = Math.floor(rng() * 1920);
      key = `${x}|${y}`;
      if (!touches.has(key)) break;
    }
    touches.add(key);

    // A reader scrolls most samples, pauses on a few. |delta| / 5s stays far
    // below SCROLL_MAX_PX_PER_SECOND.
    const scrollDelta = rng() < 0.15 ? 0 : Math.round((rng() - 0.5) * 4200);

    samples.push({
      ts: START_TS + i * SAMPLE_INTERVAL_MS,
      batteryTempC: Number(temp.toFixed(4)),
      touch: { x, y },
      scrollDelta,
    });
  }
  return samples;
}

/**
 * An EMULATOR / SERVER FARM: a stubbed sensor reporting a constant
 * temperature, a scripted tap on the exact same pixel, and a canned scroll
 * delta. No flags on this one would mean the engine is not looking.
 *
 * @param {number} [count]
 * @returns {Array<Object>}
 */
function emulatorTelemetry(count = 30) {
  const samples = [];
  for (let i = 0; i < count; i += 1) {
    samples.push({
      ts: START_TS + i * SAMPLE_INTERVAL_MS,
      batteryTempC: 30, // identical every single time
      touch: { x: 412, y: 883 }, // identical every single time
      scrollDelta: 480, // canned
    });
  }
  return samples;
}

/**
 * A BOT with human-ish hardware: the battery sensor looks fine (it may even be
 * a real phone in an automated test rig), but the touch is a replayed script
 * on one pixel and one interval teleports the viewport.
 *
 * @param {number} [count]
 * @returns {Array<Object>}
 */
function botTouchTelemetry(count = 30) {
  const rng = _rng(0xb07);
  const samples = [];
  let temp = 31.2;
  for (let i = 0; i < count; i += 1) {
    temp += (rng() - 0.5) * 0.7;
    const inhuman = i === 9;
    samples.push({
      ts: START_TS + i * SAMPLE_INTERVAL_MS,
      batteryTempC: Number(temp.toFixed(4)),
      touch: { x: 412, y: 883 }, // replayed coordinate, every sample
      // 90_000 px in 5s = 18_000 px/s, 4.5x the human ceiling.
      scrollDelta: inhuman ? 90000 : Math.round((rng() - 0.5) * 3000),
    });
  }
  return samples;
}

/* -------------------------------------------------------------------------- */
/* 1. Telemetry                                                               */
/* -------------------------------------------------------------------------- */

test("human telemetry: no flags, pristine score, acceptable", () => {
  const samples = humanTelemetry();
  const result = evaluateTelemetry(samples);
  assert.deepEqual(result.flags, [], `expected a clean bill of health, got ${result.flags}`);
  assert.equal(result.score, 100);
  assert.ok(result.score >= TELEMETRY_PASS_SCORE);
  assert.equal(isTelemetryAcceptable(result), true);
  // Guard the fixture itself: it must be a long enough, genuinely drifting run.
  assert.ok(samples.length > MIN_TELEMETRY_SAMPLES);
  const temps = samples.map((s) => s.batteryTempC);
  assert.ok(Math.max(...temps) - Math.min(...temps) > 1, "temperatures must drift");
  assert.ok(Math.min(...temps) >= 25 && Math.max(...temps) <= 40);
  const touches = new Set(samples.map((s) => `${s.touch.x}|${s.touch.y}`));
  assert.equal(touches.size, samples.length, "no repeated touch coordinate");
});

test("emulator telemetry: BATTERY_FLATLINE and PIXEL_PERFECT_TOUCH, below the threshold", () => {
  const result = evaluateTelemetry(emulatorTelemetry());
  assert.ok(result.flags.includes(FLAGS.BATTERY_FLATLINE), "flatline battery detected");
  assert.ok(result.flags.includes(FLAGS.PIXEL_PERFECT_TOUCH), "pixel-perfect touch detected");
  assert.ok(!result.flags.includes(FLAGS.BATTERY_IMPOSSIBLE), "30C is physically plausible");
  assert.ok(result.score < TELEMETRY_PASS_SCORE, `score ${result.score} must be unacceptable`);
  assert.equal(isTelemetryAcceptable(result), false);
  // Documented arithmetic: 100 - flatline(40) - pixelPerfect(25).
  assert.equal(result.score, 100 - FLAGS_PENALTIES.BATTERY_FLATLINE - FLAGS_PENALTIES.PIXEL_PERFECT_TOUCH);
});

test("emulator with no battery sensor at all: never acceptable", () => {
  const samples = humanTelemetry().map((sample) => ({ ...sample, batteryTempC: undefined }));
  const result = evaluateTelemetry(samples);
  assert.ok(result.flags.includes(FLAGS.BATTERY_IMPOSSIBLE), "a missing reading is impossible");
  assert.ok(result.flags.includes(FLAGS.BATTERY_FLATLINE), "a dead sensor is a flatline");
  assert.ok(result.score < TELEMETRY_PASS_SCORE);
  assert.equal(isTelemetryAcceptable(result), false);
});

test("bot telemetry: PIXEL_PERFECT_TOUCH and INHUMAN_SCROLL_SPEED, unacceptable", () => {
  const result = evaluateTelemetry(botTouchTelemetry());
  assert.ok(result.flags.includes(FLAGS.PIXEL_PERFECT_TOUCH), "replayed touch detected");
  assert.ok(result.flags.includes(FLAGS.INHUMAN_SCROLL_SPEED), "impossible scroll detected");
  assert.ok(!result.flags.includes(FLAGS.BATTERY_FLATLINE), "the temperature really does drift");
  assert.ok(!result.flags.includes(FLAGS.BATTERY_IMPOSSIBLE), "the temperature is plausible");
  assert.ok(result.score < TELEMETRY_PASS_SCORE, `score ${result.score} must be unacceptable`);
  assert.equal(isTelemetryAcceptable(result), false);
});

test("a human-plausible fast flick is NOT flagged as inhuman scroll", () => {
  // ~1500 px/s sustained: a hard flick on a high-refresh panel, still human.
  const samples = humanTelemetry(10).map((sample, i) => ({
    ...sample,
    scrollDelta: i === 0 ? 0 : 7500,
  }));
  const result = evaluateTelemetry(samples);
  assert.ok(!result.flags.includes(FLAGS.INHUMAN_SCROLL_SPEED));
  assert.equal(isTelemetryAcceptable(result), true);
});

test("impossible battery values: 5C, 90C and NaN all raise BATTERY_IMPOSSIBLE", () => {
  for (const badTemp of [5, -40, 90, NaN, null, undefined, "31", Infinity]) {
    const samples = humanTelemetry().map((sample, i) =>
      i === 3 ? { ...sample, batteryTempC: badTemp } : sample
    );
    const result = evaluateTelemetry(samples);
    assert.ok(
      result.flags.includes(FLAGS.BATTERY_IMPOSSIBLE),
      `batteryTempC ${String(badTemp)} must be impossible`
    );
    // A single impossible reading in an otherwise clean 30-sample run costs the
    // documented penalty but does not by itself disqualify the session: the
    // other 29 samples are the evidence, and the burden is on the flag to
    // combine with a second signal to cross TELEMETRY_PASS_SCORE.
    assert.equal(result.score, 100 - FLAGS_PENALTIES.BATTERY_IMPOSSIBLE);
    assert.ok(!result.flags.includes(FLAGS.BATTERY_FLATLINE));
  }
});

test("impossible battery on EVERY sample: a dead sensor is never acceptable", () => {
  const samples = humanTelemetry().map((sample) => ({ ...sample, batteryTempC: 5 }));
  const result = evaluateTelemetry(samples);
  assert.ok(result.flags.includes(FLAGS.BATTERY_IMPOSSIBLE));
  assert.ok(result.flags.includes(FLAGS.BATTERY_FLATLINE), "a constant 5C is a stubbed sensor");
  assert.equal(result.score, 100 - FLAGS_PENALTIES.BATTERY_IMPOSSIBLE - FLAGS_PENALTIES.BATTERY_FLATLINE);
  assert.ok(result.score < TELEMETRY_PASS_SCORE);
  assert.equal(isTelemetryAcceptable(result), false);
});

test("a missing or non-numeric ts is treated as a fabricated record", () => {
  for (const badTs of [undefined, null, NaN, "0", {}]) {
    const samples = humanTelemetry().map((sample, i) => (i === 2 ? { ...sample, ts: badTs } : sample));
    const result = evaluateTelemetry(samples);
    assert.ok(result.flags.includes(FLAGS.BATTERY_IMPOSSIBLE), `ts ${String(badTs)}`);
  }
});

test("too few samples: a short stream is a FAIL, not a pass", () => {
  const result = evaluateTelemetry(humanTelemetry(MIN_TELEMETRY_SAMPLES - 1));
  assert.ok(result.flags.includes(FLAGS.TOO_FEW_SAMPLES));
  assert.equal(result.score, 0, "TOO_FEW_SAMPLES alone must zero the score");
  assert.equal(isTelemetryAcceptable(result), false);
});

test("exactly MIN_TELEMETRY_SAMPLES is enough to avoid TOO_FEW_SAMPLES", () => {
  const result = evaluateTelemetry(humanTelemetry(MIN_TELEMETRY_SAMPLES));
  assert.ok(!result.flags.includes(FLAGS.TOO_FEW_SAMPLES));
  assert.equal(result.score, 100);
});

test("degenerate telemetry input: empty array scores 0, does not throw; non-array throws TypeError", () => {
  const empty = evaluateTelemetry([]);
  assert.deepEqual(empty, { score: 0, flags: [FLAGS.TOO_FEW_SAMPLES] });

  for (const bad of [undefined, null, "samples", 42, {}, new Set()]) {
    assert.throws(() => evaluateTelemetry(bad), TypeError, `input ${String(bad)}`);
  }
});

test("garbage records inside an array do not throw", () => {
  const samples = [null, undefined, 7, "nope", {}, { ts: 1, batteryTempC: 20, scrollDelta: 0 }];
  const result = evaluateTelemetry(samples);
  assert.equal(typeof result.score, "number");
  assert.ok(result.flags.includes(FLAGS.TOO_FEW_SAMPLES));
  assert.ok(result.flags.includes(FLAGS.BATTERY_IMPOSSIBLE));
});

test("evaluateTelemetry is pure: same input twice => deep-equal, input untouched", () => {
  const samples = humanTelemetry();
  const snapshot = structuredClone(samples);
  const first = evaluateTelemetry(samples);
  const second = evaluateTelemetry(samples);
  assert.deepEqual(second, first);
  assert.deepEqual(samples, snapshot, "the engine must not mutate the caller's array");
  // Same again through a reversed-shaped copy: still deterministic.
  assert.deepEqual(evaluateTelemetry(structuredClone(snapshot)), first);
});

test("isTelemetryAcceptable rejects junk results", () => {
  for (const bad of [undefined, null, {}, "PASS", { score: "100" }, { score: NaN }]) {
    assert.equal(isTelemetryAcceptable(bad), false);
  }
  assert.equal(isTelemetryAcceptable({ score: TELEMETRY_PASS_SCORE }), true);
  assert.equal(isTelemetryAcceptable({ score: TELEMETRY_PASS_SCORE - 1 }), false);
});

/* -------------------------------------------------------------------------- */
/* 2. Submission                                                              */
/* -------------------------------------------------------------------------- */

const ARTICLE = getArticle("art-focus-101");
const MISSION = getMission("mission-1");

/**
 * Counts the characters the engine will charge for: the selected option texts
 * plus the submitted highlight length.
 *
 * @param {Object} article
 * @param {Array<{ questionId: string, answerIndex: number }>} answers
 * @param {string} highlight
 * @returns {number}
 */
function impliedChars(article, answers, highlight) {
  const byId = new Map(answers.map((a) => [a.questionId, a.answerIndex]));
  let chars = highlight.length;
  for (const question of article.quiz) {
    const selected = byId.get(question.id);
    if (Number.isInteger(selected)) chars += question.options[selected].length;
  }
  return chars;
}

const CORRECT_ANSWERS = ARTICLE.quiz.map((q) => ({
  questionId: q.id,
  answerIndex: q.correctIndex,
}));
const GOOD_HIGHLIGHT = ARTICLE.highlightTask.keySentences.join(" ... ");

function submission(overrides = {}) {
  const base = {
    answers: CORRECT_ANSWERS,
    highlight: GOOD_HIGHLIGHT,
    typingMs: impliedChars(ARTICLE, CORRECT_ANSWERS, GOOD_HIGHLIGHT) * 120, // 120ms/char
    telemetryScore: 100,
    mission: MISSION,
    article: ARTICLE,
  };
  return { ...base, ...overrides };
}

test("a correct, human-paced submission with good telemetry PASSes and pays out", () => {
  const result = evaluateSubmission(submission());
  assert.equal(result.status, PASS);
  assert.equal(result.status, STATUS.PASS);
  assert.equal(result.status, "PASS");
  assert.deepEqual(result.flags, []);
  assert.equal(result.reward, MISSION.reward);
  assert.equal(result.staminaCost, MISSION.staminaCost);
  assert.equal(result.details.correctAnswers, result.details.totalQuestions);
  assert.equal(result.details.correctAnswers, ARTICLE.quiz.length);
  assert.ok(result.details.highlightMatches >= result.details.minMatches);
  assert.ok(result.details.impliedMs >= result.details.floorMs);
  assert.equal(result.details.floorMs, result.details.impliedChars * MIN_TYPING_MS_PER_CHAR);
});

test("a wrong answer FAILS with the quiz flag and pays nothing", () => {
  const answers = CORRECT_ANSWERS.map((answer, i) =>
    i === 1 ? { ...answer, answerIndex: (answer.answerIndex + 1) % 4 } : answer
  );
  const result = evaluateSubmission(submission({ answers }));
  assert.equal(result.status, FAIL);
  assert.ok(result.flags.includes(SUBMISSION_FLAGS.QUIZ_INCORRECT));
  assert.equal(result.reward, 0);
  assert.equal(
    result.staminaCost,
    MISSION.staminaCost,
    "stamina is charged for the attempt even on failure"
  );
  assert.equal(result.details.correctAnswers, ARTICLE.quiz.length - 1, "no partial credit");
});

test("partial credit is not allowed: 2 of 3 correct is a FAIL", () => {
  const answers = CORRECT_ANSWERS.slice(0, 2);
  const result = evaluateSubmission(submission({ answers }));
  assert.equal(result.status, FAIL);
  assert.ok(result.flags.includes(SUBMISSION_FLAGS.QUIZ_INCORRECT));
  assert.equal(result.details.correctAnswers, 2);
  assert.equal(result.details.answeredQuestions, 2);
});

test("a highlight that misses the key sentences FAILS with the highlight flag", () => {
  const result = evaluateSubmission(
    submission({ highlight: "I read the whole thing and it was fine, nothing to report." })
  );
  assert.equal(result.status, FAIL);
  assert.ok(result.flags.includes(SUBMISSION_FLAGS.HIGHLIGHT_MISSING));
  assert.equal(result.details.highlightMatches, 0);
  assert.equal(result.reward, 0);
});

test("highlight matching is case- and punctuation-insensitive", () => {
  const mangled = GOOD_HIGHLIGHT.toUpperCase().replace(/[.]/g, "!!!");
  const result = evaluateSubmission(submission({ highlight: mangled }));
  assert.ok(!result.flags.includes(SUBMISSION_FLAGS.HIGHLIGHT_MISSING), JSON.stringify(result.flags));
  assert.equal(result.status, PASS);
});

test("one key sentence out of two is not enough when minMatches is 2", () => {
  const result = evaluateSubmission(
    submission({ highlight: ARTICLE.highlightTask.keySentences[0] })
  );
  assert.equal(result.status, FAIL);
  assert.ok(result.flags.includes(SUBMISSION_FLAGS.HIGHLIGHT_MISSING));
  assert.equal(result.details.highlightMatches, 1);
  assert.equal(result.details.minMatches, ARTICLE.highlightTask.minMatches);
});

test("typing far below the floor FAILS with TYPING_TOO_FAST", () => {
  const result = evaluateSubmission(submission({ typingMs: 12 }));
  assert.equal(result.status, FAIL);
  assert.ok(result.flags.includes(SUBMISSION_FLAGS.TYPING_TOO_FAST));
  assert.ok(result.details.impliedMs < result.details.floorMs);
  assert.equal(result.reward, 0);
  assert.equal(result.staminaCost, MISSION.staminaCost);
});

test("typing exactly at the floor passes, one millisecond below fails", () => {
  const floor = impliedChars(ARTICLE, CORRECT_ANSWERS, GOOD_HIGHLIGHT) * MIN_TYPING_MS_PER_CHAR;
  assert.equal(evaluateSubmission(submission({ typingMs: floor })).status, PASS);
  assert.equal(evaluateSubmission(submission({ typingMs: floor - 1 })).status, FAIL);
});

test("a poor telemetry score FAILS with TELEMETRY_POOR", () => {
  const result = evaluateSubmission(submission({ telemetryScore: TELEMETRY_PASS_SCORE - 1 }));
  assert.equal(result.status, FAIL);
  assert.ok(result.flags.includes(SUBMISSION_FLAGS.TELEMETRY_POOR));
  assert.equal(result.reward, 0);
  assert.equal(
    evaluateSubmission(submission({ telemetryScore: TELEMETRY_PASS_SCORE })).status,
    PASS,
    "the threshold itself passes"
  );
});

test("the two signals compose: a good reader on a bad device is still rejected", () => {
  const samples = emulatorTelemetry();
  const telemetry = evaluateTelemetry(samples);
  assert.equal(isTelemetryAcceptable(telemetry), false);
  const result = evaluateSubmission(submission({ telemetryScore: telemetry.score }));
  assert.equal(result.status, FAIL);
  assert.ok(result.flags.includes(SUBMISSION_FLAGS.TELEMETRY_POOR));
  assert.equal(result.reward, 0);
  assert.equal(result.staminaCost, MISSION.staminaCost);
});

test("malformed submissions return FAIL with flags instead of throwing", () => {
  const garbage = [
    {},
    { answers: "none", highlight: 5, typingMs: "fast", telemetryScore: "high" },
    { answers: [null, 3, "x"], highlight: null, typingMs: NaN, telemetryScore: undefined },
    { answers: [], highlight: "", typingMs: 0, telemetryScore: 0, mission: null, article: null },
  ];
  for (const payload of garbage) {
    const result = evaluateSubmission(payload);
    assert.equal(result.status, FAIL);
    assert.equal(result.reward, 0);
    assert.ok(result.flags.length > 0);
    assert.ok(result.flags.includes(SUBMISSION_FLAGS.SUBMISSION_MALFORMED), JSON.stringify(result.flags));
    assert.equal(typeof result.staminaCost !== "undefined", true);
  }
  // A submission with no mission has no stamina to charge, and says so.
  assert.equal(evaluateSubmission({}).staminaCost, 0);
});

test("a non-object submission throws TypeError (programming error, not an attack)", () => {
  for (const bad of [undefined, null, "payload", 7, true, []]) {
    assert.throws(() => evaluateSubmission(bad), TypeError, `payload ${String(bad)}`);
  }
});

test("evaluateSubmission is pure and deterministic: the article is not mutated", () => {
  const articleSnapshot = structuredClone(ARTICLE);
  const missionSnapshot = structuredClone(MISSION);
  const answers = structuredClone(CORRECT_ANSWERS);
  const first = evaluateSubmission(submission());
  const second = evaluateSubmission(submission());
  assert.deepEqual(second, first);
  assert.deepEqual(ARTICLE, articleSnapshot, "the seeded article must survive grading");
  assert.deepEqual(MISSION, missionSnapshot);
  assert.deepEqual(answers, CORRECT_ANSWERS, "the caller's answers array is untouched");
});

/* -------------------------------------------------------------------------- */
/* 3. similarity                                                              */
/* -------------------------------------------------------------------------- */

test("similarity: identical text scores exactly 1", () => {
  assert.equal(similarity("the spacing effect beats cramming", "the spacing effect beats cramming"), 1);
  assert.equal(similarity("Same Words Here", "same words here"), 1, "case does not matter");
  assert.equal(similarity("hard, fast; precise!!", "hard fast precise"), 1, "punctuation does not matter");
});

test("similarity: empty vs empty is 1, one-sided empty is 0", () => {
  assert.equal(similarity("", ""), 1);
  assert.equal(similarity("   ", ""), 1, "whitespace-only normalizes to empty");
  assert.equal(similarity("a", ""), 0);
  assert.equal(similarity("", "a"), 0);
});

test("similarity: disjoint text scores 0 and is symmetric", () => {
  assert.equal(similarity("alpha beta", "gamma delta"), 0);
  const a = "desirable difficulty sits on the retrieval side";
  const b = "sponsored bonds accrue yield to stakers";
  assert.equal(similarity(a, b), 0);
  assert.equal(similarity(a, b), similarity(b, a), "symmetry");
  assert.equal(similarity(a, a), similarity(a, a));
});

test("similarity: partial overlap lands strictly between 0 and 1", () => {
  const score = similarity("attention drifts before the tank is empty", "attention drifts after a long walk");
  assert.ok(score > 0 && score < 1, `expected a partial score, got ${score}`);
  assert.equal(score, similarity("attention drifts after a long walk", "attention drifts before the tank is empty"));
});

test("similarity: the result is always a number in [0, 1], even for junk input", () => {
  for (const [a, b] of [
    [undefined, null],
    [42, {}],
    ["", undefined],
    ["!!!", "???"],
  ]) {
    const score = similarity(a, b);
    assert.equal(typeof score, "number");
    assert.ok(score >= 0 && score <= 1);
  }
});

test("normalizeText: lowercase, punctuation stripped, whitespace collapsed", () => {
  assert.equal(normalizeText("Hello,   World!  Again--now."), "hello world again now");
  assert.equal(normalizeText("  "), "");
  assert.equal(normalizeText(undefined), "");
  assert.equal(normalizeText(12), "");
  assert.equal(similarity("A b", normalizeText("A  b!!")), 1);
});

/* -------------------------------------------------------------------------- */
/* 4. detectSyndicate                                                         */
/* -------------------------------------------------------------------------- */

test("detectSyndicate: an empty history is never a syndicate", () => {
  assert.deepEqual(detectSyndicate({ previousTexts: [], currentText: "anything at all" }), {
    syndicate: false,
    similarity: 0,
  });
  assert.deepEqual(detectSyndicate({}), { syndicate: false, similarity: 0 });
  assert.deepEqual(detectSyndicate({ previousTexts: "not an array", currentText: "x" }), {
    syndicate: false,
    similarity: 0,
  });
});

test("detectSyndicate: a >90% identical history IS flagged", () => {
  const canonical =
    "The difficulty has to be on the retrieval side, and the session is reporting fluency rather than retention.";
  const history = [canonical];
  const nearCopy =
    "The difficulty has to be on the retrieval side and the session is reporting fluency rather than retention!";
  const result = detectSyndicate({ previousTexts: history, currentText: nearCopy });
  assert.equal(result.syndicate, true);
  assert.ok(
    result.similarity > SYNDICATE_SIMILARITY_THRESHOLD,
    `expected > ${SYNDICATE_SIMILARITY_THRESHOLD}, got ${result.similarity}`
  );
  assert.ok(result.similarity <= 1);
});

test("detectSyndicate: an exactly copied answer is flagged with similarity 1", () => {
  const text = "attention drifts in bursts, not smoothly";
  const result = detectSyndicate({ previousTexts: ["something else entirely", text], currentText: text });
  assert.deepEqual(result, { syndicate: true, similarity: 1 });
});

test("detectSyndicate: a genuinely different answer is not flagged", () => {
  const result = detectSyndicate({
    previousTexts: [
      "the spacing effect beats cramming because contextual cues are removed",
      "interleaving forces the learner to choose a procedure on every item",
    ],
    currentText: "I highlighted the passage about switching costs and delegation",
  });
  assert.equal(result.syndicate, false);
  assert.ok(result.similarity < SYNDICATE_SIMILARITY_THRESHOLD);
});

test("detectSyndicate: it compares against the BEST match, not the average", () => {
  const text = "a short canonical answer about retrieval difficulty";
  const result = detectSyndicate({
    previousTexts: ["totally unrelated text about keyboards", text, "more unrelated filler text"],
    currentText: text,
  });
  assert.equal(result.syndicate, true);
  assert.equal(result.similarity, 1);
});

/* -------------------------------------------------------------------------- */
/* 5. Thresholds as a contract                                                */
/* -------------------------------------------------------------------------- */

test("the exported thresholds are the documented ones", () => {
  assert.equal(MIN_TELEMETRY_SAMPLES, 8);
  assert.equal(TELEMETRY_PASS_SCORE, 60);
  assert.equal(SCROLL_MAX_PX_PER_SECOND, 4000);
  assert.equal(MIN_TYPING_MS_PER_CHAR, 60);
  assert.equal(SYNDICATE_SIMILARITY_THRESHOLD, 0.9);
  assert.equal(FLAGS.BATTERY_FLATLINE, "BATTERY_FLATLINE");
  assert.equal(FLAGS.BATTERY_IMPOSSIBLE, "BATTERY_IMPOSSIBLE");
  assert.equal(FLAGS.PIXEL_PERFECT_TOUCH, "PIXEL_PERFECT_TOUCH");
  assert.equal(FLAGS.INHUMAN_SCROLL_SPEED, "INHUMAN_SCROLL_SPEED");
  assert.equal(FLAGS.TOO_FEW_SAMPLES, "TOO_FEW_SAMPLES");
  assert.equal(SUBMISSION_FLAGS.QUIZ_INCORRECT, "QUIZ_INCORRECT");
  assert.equal(SUBMISSION_FLAGS.HIGHLIGHT_MISSING, "HIGHLIGHT_MISSING");
  assert.equal(SUBMISSION_FLAGS.TYPING_TOO_FAST, "TYPING_TOO_FAST");
  assert.equal(SUBMISSION_FLAGS.TELEMETRY_POOR, "TELEMETRY_POOR");
  assert.equal(SUBMISSION_FLAGS.SUBMISSION_MALFORMED, "SUBMISSION_MALFORMED");
  assert.equal(FAIL, "FAIL");
  assert.deepEqual(FLAGS_PENALTIES, {
    BATTERY_FLATLINE: 40,
    BATTERY_IMPOSSIBLE: 30,
    PIXEL_PERFECT_TOUCH: 25,
    INHUMAN_SCROLL_SPEED: 20,
    TOO_FEW_SAMPLES: 100,
  });
});

module.exports = {
  humanTelemetry,
  emulatorTelemetry,
  botTouchTelemetry,
};
